---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: ['--branch', 'master']
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.24.2
    hooks:
      - id: yamllint
        args: ['-d relaxed']

  - repo: git://github.com/kintoandar/pre-commit
    rev: v2.1.0
    hooks:
    - id: terraform_fmt
    # - id: terraform_validate
    # - id: prometheus_check_rules
    # - id: prometheus_check_config

  - repo: https://github.com/ansible/ansible-lint
    rev: v4.3.4
    hooks:
      - id: ansible-lint

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
      - id: rubocop
        args: [
          '--auto-correct',
          '--except',' Naming/FileName,Metrics/BlockLength'
          ]
