---

- name: install mathematica

  vars:
    mnt_software: /mnt/software

  block:

    - import_tasks: tasks/utils/mount_software.yml

    - name: install Mathematica dependencies
      become: yes
      apt:
        name:
          - avahi-daemon
          - qt5-default       # Should cover most of what's required. The others are "just in case".
          - xauth
          - fontconfig
          - libglu1-mesa
          - libasound2

    - name: run Mathematica installer silently
      become: yes
      vars:
        mathematica_path: /usr/local/Wolfram/Mathematica/11.2
      shell:
        executable: /bin/bash
        cmd: "{{ item }}"
        creates: "{{ mathematica_path }}/Configuration/Licensing/mathpass"
      with_items:
        - "sh {{ mnt_software }}/Mathematica/Mathematica_11.2.0_LINUX.sh -- -silent"
        - "cp {{ mnt_software }}/Mathematica/mathpass {{ mathematica_path }}/Configuration/Licensing/mathpass"

  always:
    - import_tasks: tasks/utils/unmount_software.yml
