---

- name: download DS9
  become: yes
  get_url:
    url: http://ds9.si.edu/download/ubuntu18/ds9.ubuntu18.8.1.tar.gz
    dest: /tmp/ds9.tar.gz

- name: install DS9
  become: yes
  unarchive:
    src: /tmp/ds9.tar.gz
    dest: /usr/local/bin/
    remote_src: yes

- name: delete ds9.tar.gz
  become: yes
  file:
    path: /tmp/ds9.tar.gz
    state: absent
