---

- name: perform a full upgrade
  become: true
  apt:
    upgrade: dist
    update_cache: yes
    dpkg_options: 'force-confold,force-confdef'

- name: apt install packages
  become: true
  apt:
    name: "{{ apt_packages }}"
    update_cache: yes
    cache_valid_time: 3600
