---

- name: clone PyWiFeS
  become: yes
  git:
    repo: https://github.com/PyWiFeS/pipeline.git
    dest: /usr/local/pywifes

- name: copy pywifes conda env file
  copy:
    src: "files2copy/env_pywifes.yml"
    dest: "$HOME/env_pywifes.yml"

- name: create conda env for pywifes
  shell:
    chdir: "$HOME"
    executable: /bin/bash
    cmd: "{{ item }}"
  with_items:
    - "conda env create --force -f env_pywifes.yml"
    - "source .bashrc && conda activate pywifes && conda develop /usr/local/pywifes/src"

- name: set $PYWIFES_DIR in .bashrc
  lineinfile:
    path: $HOME/.bashrc
    line: export PYWIFES_DIR=/usr/local/pywifes/reference_data

- name: remove conda env file
  file:
    path: "$HOME/env_pywifes.yml"
    state: absent
