SOURCE_IMAGE_NAME='NeCTAR CentOS 8 x86_64'
DEFAULT_USER='ec2-user'
IMAGE_TAGNAME='image_abaqus'
IMAGE_FULLNAME='ADACS (with ABAQUS) - CentOS 8 x86_64'
IMAGE_STAGENAME="staging_${IMAGE_TAGNAME}"
TEST_SERVER_NAME="testing_${IMAGE_TAGNAME}"
COMMUNITY_IMAGE='no'
