SOURCE_IMAGE_NAME='NeCTAR Ubuntu 18.04 LTS (Bionic) amd64'
DEFAULT_USER='ubuntu'
IMAGE_TAGNAME='image_mathematica'
IMAGE_FULLNAME='ADACS (with Mathematica) - Ubuntu 18.04 LTS (Bionic) amd64'
IMAGE_STAGENAME="staging_${IMAGE_TAGNAME}"
TEST_SERVER_NAME="testing_${IMAGE_TAGNAME}"
COMMUNITY_IMAGE='no'
