---

- name: download miniconda
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: "{{ home_dir }}/miniconda.sh"

- name: install miniconda
  shell:
    chdir: "{{ home_dir }}"
    creates: "{{ home_dir }}/miniconda"
    executable: /bin/bash
    cmd: bash miniconda.sh -b -p miniconda

- name: "conda: init, install packages, and clean"
  shell:
    chdir: "{{ home_dir }}"
    executable: /bin/bash
    cmd: "{{ item }}"
  with_items:
    - "source miniconda/bin/activate && conda init"
    - "source miniconda/bin/activate && conda install -y {{ conda_packages | join(' ')}}"
    - "source miniconda/bin/activate && conda clean -y --all"

- name: remove default conda env prefix (base) from command prompt
  blockinfile:
    path: ~/.bashrc
    block: PS1=${PS1/"(base) "/""}
    marker: "{mark}"
    marker_begin: "\n# >>> BEGIN remove default conda env prefix (base) from command prompt"
    marker_end: "# <<< END"
