---

- name: install Mathematica dependencies
  become: yes
  apt:
    name:
      - avahi-daemon
      - qt5-default       # Should cover most of what's required. The others are "just in case".
      - xauth
      - fontconfig
      - libglu1-mesa
      - libasound2
    update_cache: yes

- name: mount volume containing software
  become: yes
  mount:
    src: /dev/vdb
    path: /mnt/software
    state: mounted
    fstype: ext4
    opts: ro

- name: run Mathematica installer silently
  become: yes
  shell:
    executable: /bin/bash
    cmd: "{{ item }}"
  with_items:
    - "sh /mnt/software/Mathematica/Mathematica_11.2.0_LINUX.sh -- -silent"
    - "cp /mnt/software/Mathematica/mathpass /usr/local/Wolfram/Mathematica/11.2/Configuration/Licensing/mathpass"

- name: unmount software volume
  become: yes
  mount:
    path: /mnt/software
    state: absent

