---

- name: Provision the image
  hosts: default
  gather_facts: yes
  become: no

  # save /home/ubuntu, useful when running module as root and you cant use $HOME
  vars:
    home_dir: "{{ ansible_facts['env']['HOME'] }}"

  vars_files:
    - vars/apt_packages.yml
    - vars/conda_packages.yml

  tasks:
    - wait_for_connection:
    - import_tasks: tasks/provision.yml
    - import_tasks: tasks/cleanup.yml
