---

- name: Provision the image
  hosts: default
  gather_facts: yes
  become: no

  vars:
    home_dir: "{{ ansible_facts['env']['HOME'] }}" #/home/ubuntu

  vars_files:
    - vars/apt_packages.yml
    - vars/conda_packages.yml

  tasks:
    - wait_for_connection:
    - import_tasks: tasks/provision.yml
    - import_tasks: tasks/cleanup.yml
