# This is a basic workflow to help you get started with Actions

name: build + test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - image_astro_A
          - image_astro_A_intel_idl
          - image_astro_B
          - image_basic
          - image_idl
          - image_intel
          - image_intel_idl_conda
          - image_mathematica
          - image_matlab

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # # Runs a single command using the runners shell
    # - name: Run a one-line script
    #   run:

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        set -a
        source image_vars/${{ matrix.image }}.sh
        echo ${IMAGE_TAGNAME}
        echo ${NEW_IMAGE_NAME}
        echo ${ANSIBLE_IMAGE_FILE}
        echo ${INSPEC_PROFILE}
        pwd
        ls
