name: build + test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
  OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
  OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
  OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
  OS_USERNAME: ${{ secrets.OS_USERNAME }}
  OS_USER_DOMAIN_NAME: "Default"
  OS_PROJECT_DOMAIN_ID: "default"
  OS_REGION_NAME: "Melbourne"
  OS_INTERFACE: public
  OS_IDENTITY_API_VERSION: 3

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - image_astro_A
          - image_astro_A_intel_idl
          - image_astro_B
          - image_basic
          - image_idl
          - image_intel
          - image_intel_idl_conda
          - image_mathematica
          - image_matlab
    steps:
    - uses: actions/checkout@v2
    - name: Install Chef Inspec
      run: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
    - name: Run test script
      run: |
        set -a
        source image_vars/${{ matrix.image }}.sh
        ./test.sh
