name: build + test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OS_AUTH_TYPE: ${{ secrets.OS_AUTH_TYPE }}
  OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
  OS_IDENTITY_API_VERSION: ${{ secrets.OS_IDENTITY_API_VERSION }}
  OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
  OS_INTERFACE: ${{ secrets.OS_INTERFACE }}
  OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
  OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}

jobs:
  CICD:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        image:
          - image_basic
          - image_astro_A
          - image_astro_A_intel_idl
          - image_astro_B
          - image_idl
          - image_intel
          - image_intel_idl_conda
          - image_mathematica
          - image_matlab

    steps:
    - uses: actions/checkout@v2

    # Installations
    - run: sudo apt-get update

    - name: Install Chef Inspec
      run: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec

    - name: Install OpenStack client
      run: sudo apt-get install python-openstackclient

    - name: Install Nova client
      run: sudo apt-get install python-novaclient

    # Building
    - name: Check if there are enough cores available for launching BUILD VM
      run: ./openstack_check.sh

    - name: Run build script
      run: IMG=image_vars/${{ matrix.image }}.sh ./build.sh

    # Testing
    - name: Check if there are enough cores available for launching TEST VM
      run: ./openstack_check.sh

    - name: Run test script
      run: IMG=image_vars/${{ matrix.image }}.sh ./test.sh

    # Only deploy when commit contains a release tag
    - name: Deploy Image
      if: github.event_name == 'push' && contains(github.ref, '/tags/release')
      run: IMG=image_vars/${{ matrix.image }}.sh ./deploy.sh
