name: ADACS image build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OS_AUTH_TYPE: ${{ secrets.OS_AUTH_TYPE }}
  OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
  OS_IDENTITY_API_VERSION: ${{ secrets.OS_IDENTITY_API_VERSION }}
  OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
  OS_INTERFACE: ${{ secrets.OS_INTERFACE }}
  OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
  OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
  TF_CLI_ARGS: -no-color
  ANSIBLE_NOCOLOR: 1

jobs:
  start_nfs:
    runs-on: ubuntu-latest
    if: "always()"
    defaults:
      run:
        working-directory: ./build/nfs

    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Apply
      run: terraform apply -auto-approve > /dev/null

  build:
    needs: start_nfs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - image_basic
          - image_astro_A
          - image_astro_A_intel_idl
          - image_astro_B
          - image_idl
          - image_intel
          - image_intel_idl_conda
          - image_mathematica
          - image_matlab
          - image_abaqus

    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_wrapper: false

    - uses: ./.github/actions/install-tools

    - name: Run build script
      working-directory: build
      run: ./build.sh ../image_vars/${{ matrix.image }}.sh.hcl

    - name: Run test script
      working-directory: test
      run: ./test.sh ../image_vars/${{ matrix.image }}.sh.hcl

    - name: Deploy Image
      run: ./deploy.sh ./image_vars/${{ matrix.image }}.sh.hcl

  stop_nfs:
    needs: CICD
    runs-on: ubuntu-latest
    if: "always()"
    defaults:
      run:
        working-directory: ./build/nfs

    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Destroy
      run: terraform destroy -auto-approve > /dev/null
