name: build + test + deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OS_AUTH_TYPE: ${{ secrets.OS_AUTH_TYPE }}
  OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
  OS_IDENTITY_API_VERSION: ${{ secrets.OS_IDENTITY_API_VERSION }}
  OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
  OS_INTERFACE: ${{ secrets.OS_INTERFACE }}
  OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
  OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}

jobs:
  CICD:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        image:
          - image_basic
          - image_astro_A
          - image_astro_A_intel_idl
          - image_astro_B
          - image_idl
          - image_intel
          - image_intel_idl_conda
          - image_mathematica
          - image_matlab

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/install-tools

    - name: Run build script
      run: ./build/build.sh --image ./image_vars/${{ matrix.image }}.sh

    - name: Run test script
      run: ./test/test.sh --image ./image_vars/${{ matrix.image }}.sh

    # Only deploy when commit contains a release tag
    - name: Deploy Image
      if: github.event_name == 'push' && contains(github.ref, '/tags/release')
      run: ./deploy.sh --image ./image_vars/${{ matrix.image }}.sh
