name: ADACS image build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OS_AUTH_TYPE: v3applicationcredential
  OS_AUTH_URL: https://keystone.rc.nectar.org.au:5000/v3/
  OS_IDENTITY_API_VERSION: 3
  OS_REGION_NAME: Melbourne
  OS_INTERFACE: public
  OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
  OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
  TF_CLI_ARGS: -no-color
  ANSIBLE_NOCOLOR: 1

jobs:
  start_nfs:
    runs-on: ubuntu-latest
    if: "always()"
    outputs:
      max_parallel: ${{ steps.maxp.outputs.max_parallel }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_wrapper: false

    - name: Terraform apply
      working-directory: ./build/nfs
      run: |
        terraform init
        terraform fmt -check
        terraform apply -auto-approve > /dev/null

    - uses: ./.github/actions/install-tools

    - name: Get max parallel for build step
      id: maxp
      run: |
        source utils/functions.sh
        check_installed openstack
        check_openstack_credentials
        echo ::set-output name=max_parallel::$(get_max_parallel)


  build:
    needs: start_nfs
    runs-on: ubuntu-latest
    strategy:
      max-parallel: ${{ fromJSON(needs.start_nfs.outputs.max_parallel) }}
      fail-fast: false
      matrix:
        image:
          - image_astro_A_intel_idl
          - image_astro_C
          - image_astro_B
          - image_astro_A
          - image_intel_idl_conda
          - image_abaqus
          - image_matlab
          - image_mathematica
          - image_intel
          - image_idl
          - image_basic

    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_wrapper: false

    - uses: ./.github/actions/install-tools

    - name: build -> test -> release
      run: ./run.sh ./image_vars/${{ matrix.image }}.sh

    # If job gets cancelled, GitHub only waits 7.5s, which is not long enough for packer to clean up after itself
    - name: cleanup
      if: always()
      run: |
        source ./image_vars/${{ matrix.image }}.sh
        set +e
        for item in $IMAGE_STAGENAME $TEST_SERVER_NAME; do
          openstack server show -f shell $item > instance.info
          if (( $? == 0 )); then
            source instance.info
            openstack keypair delete $key_name
            openstack server delete $item
          fi
        done

  stop_nfs:
    needs: build
    runs-on: ubuntu-latest
    if: "always()"

    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_wrapper: false

    - name: Terraform destroy
      working-directory: ./build/nfs
      run: |
        terraform init
        terraform fmt -check
        terraform destroy -auto-approve > /dev/null
